//
//	VidyoVirtualDeviceManager_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoDevice_Objc.h"
#import "VidyoEndpoint_Objc.h"
#import "VidyoLocalCamera_Objc.h"
#import "VidyoLocalMicrophone_Objc.h"
#import "VidyoLocalSpeaker_Objc.h"
@interface VCVirtualDeviceManager : NSObject
{
	void* objPtr;
}

	-(void) dealloc;
	-(BOOL) localCameraEvent:(VCEndpoint*)endpoint Camera:(VCLocalCamera*)camera State:(VCDeviceState)state;
	-(BOOL) localMicrophoneEvent:(VCEndpoint*)endpoint Microphone:(VCLocalMicrophone*)microphone State:(VCDeviceState)state;
	-(BOOL) localSpeakerEvent:(VCEndpoint*)endpoint Speaker:(VCLocalSpeaker*)speaker State:(VCDeviceState)state;
	-(BOOL) mediaFailedEvent:(VCEndpoint*)endpoint;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
