//
//	VidyoStatistics_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoMediaFormats_Objc.h"
@class VCBandwidthSummaryStats;
@class VCLatencyTestDataStats;
@class VCLatencyTestStats;
@class VCLocalMicrophoneStats;
@class VCLocalRendererStats;
@class VCLocalRendererStreamStats;
@class VCLocalSpeakerStats;
@class VCLocalSpeakerStreamStats;
@class VCLocalVideoSourceStats;
@class VCLogDataStats;
@class VCLogStats;
@class VCMediaConnectionTransportInfo;
@class VCNetworkInterfaceStats;
@class VCParticipantGenerationStats;
@class VCParticipantStats;
@class VCRateShaperStats;
@class VCRemoteMicrophoneStats;
@class VCRemoteRendererStreamStats;
@class VCRemoteSpeakerStreamStats;
@class VCRemoteVideoSourceStats;
@class VCRoomStats;
@class VCUserStats;
@interface VCBandwidthSummaryStats : NSObject
{
}

	@property size_t actualEncoderBitRate;
	@property size_t availableBandwidth;
	@property size_t leakyBucketDelay;
	@property size_t retransmitBitRate;
	@property size_t targetEncoderBitRate;
	@property size_t totalTransmitBitRate;
@end
@interface VCEndpointStats : NSObject
{
}

	@property NSMutableString* applicationTag;
	@property NSMutableString* buildTag;
	@property unsigned long long bytesReceivedTcp;
	@property unsigned long long bytesReceivedUdp;
	@property unsigned long long bytesSentTcp;
	@property unsigned long long bytesSentUdp;
	@property NSMutableString* connectTime;
	@property NSMutableString* id;
	@property NSMutableString* libraryVersion;
	@property NSMutableArray* localCameraStats;
	@property NSMutableArray* localMicrophoneStats;
	@property NSMutableArray* localMonitorStats;
	@property NSMutableArray* localRendererStats;
	@property NSMutableArray* localSpeakerStats;
	@property NSMutableArray* localWindowShareStats;
	@property VCLogStats* logStats;
	@property unsigned long long loginTimeConsumedMs;
	@property unsigned long long maxBitRate;
	@property unsigned long long maxEncodePixelRateInitial;
	@property unsigned long long mediaEnableTimeConsumedMs;
	@property unsigned long long mediaRouteAcquireTimeConsumedMs;
	@property NSMutableArray* networkInterfaceStats;
	@property NSMutableString* osName;
	@property NSMutableString* osVersion;
	@property NSMutableString* processorBrand;
	@property unsigned int processorLogicalCores;
	@property NSMutableString* processorModel;
	@property unsigned int processorPhysicalCores;
	@property unsigned int processorSpeed;
	@property unsigned long long roomEnterTimeConsumedMs;
	@property NSMutableString* timeStamp;
	@property NSMutableArray* userStats;
@end
@interface VCLatencyTestDataStats : NSObject
{
}

	@property NSMutableString* address;
	@property unsigned int latencyMs;
	@property double latitude;
	@property double longitude;
	@property NSMutableString* name;
	@property BOOL responseReceived;
@end
@interface VCLatencyTestStats : NSObject
{
}

	@property NSMutableArray* latencyTestDataStats;
@end
@interface VCLocalMicrophoneStats : NSObject
{
}

	@property unsigned int aecEchoCoupling;
	@property unsigned int agcAverageGain;
	@property unsigned int bitsPerSample;
	@property VCMediaFormat format;
	@property NSMutableString* id;
	@property NSMutableArray* localSpeakerStreams;
	@property NSMutableString* name;
	@property unsigned int noiseSuppressionSnr;
	@property unsigned int numberOfChannels;
	@property NSMutableArray* remoteSpeakerStreams;
	@property unsigned int sampleRateMeasured;
	@property unsigned int sampleRateSet;
@end
@interface VCLocalRendererStats : NSObject
{
}

	@property VCMediaFormat format;
	@property long frameIntervalMeasured;
	@property long frameIntervalSet;
	@property size_t height;
	@property NSMutableString* id;
	@property NSMutableString* name;
	@property unsigned int totalFrames;
	@property unsigned int totalPixels;
	@property size_t width;
@end
@interface VCLocalRendererStreamStats : NSObject
{
}

	@property unsigned int bufferDropped;
	@property unsigned int bufferSize;
	@property size_t height;
	@property NSMutableString* id;
	@property NSMutableString* name;
	@property size_t width;
@end
@interface VCLocalSpeakerStats : NSObject
{
}

	@property unsigned int bitsPerSample;
	@property VCMediaFormat format;
	@property NSMutableString* id;
	@property NSMutableString* name;
	@property unsigned int numberOfChannels;
	@property unsigned int sampleRateMeasured;
	@property unsigned int sampleRateSet;
@end
@interface VCLocalSpeakerStreamStats : NSObject
{
}

	@property unsigned int bitsPerSample;
	@property long delay;
	@property VCMediaFormat format;
	@property long highThreshold;
	@property long highestThreshold;
	@property BOOL isActive;
	@property int lastEnergy;
	@property long lastPlayed;
	@property long lowThreshold;
	@property long lowestThreshold;
	@property long maxThreshold;
	@property NSMutableString* name;
	@property unsigned int numberOfChannels;
	@property long overrun;
	@property long played;
	@property unsigned int sampleRate;
	@property long underrun;
@end
@interface VCLocalVideoSourceStats : NSObject
{
}

	@property VCMediaFormat format;
	@property long frameIntervalMeasured;
	@property long frameIntervalSet;
	@property size_t height;
	@property NSMutableString* id;
	@property NSMutableArray* localRendererStreams;
	@property NSMutableString* name;
	@property NSMutableArray* remoteRendererStreams;
	@property unsigned int targetBitRate;
	@property unsigned int totalFrames;
	@property size_t width;
@end
@interface VCLogDataStats : NSObject
{
}

	@property NSMutableString* name;
	@property unsigned int occurances;
@end
@interface VCLogStats : NSObject
{
}

	@property NSMutableArray* logErrorDataStats;
	@property NSMutableArray* logWarningDataStats;
@end
@interface VCMediaConnectionTransportInfo : NSObject
{
}

	@property NSMutableString* addressType;
	@property NSMutableString* componentType;
	@property unsigned int connectionId;
	@property NSMutableString* connectionType;
	@property NSMutableString* externalLocalAddr;
	@property NSMutableString* externalRemoteAddr;
	@property NSMutableString* interfaceName;
	@property NSMutableString* interfaceType;
	@property NSMutableString* internalLocalAddr;
	@property NSMutableString* internalRemoteAddr;
	@property NSMutableString* transportPlugIn;
@end
@interface VCNetworkInterfaceStats : NSObject
{
}

	@property BOOL isUp;
	@property NSMutableString* name;
	@property NSMutableString* type;
@end
@interface VCParticipantGenerationStats : NSObject
{
}

	@property NSMutableString* cameraId;
	@property NSMutableString* cameraName;
	@property BOOL enabled;
	@property long frameInterval;
	@property size_t height;
	@property NSMutableString* id;
	@property NSMutableString* name;
	@property unsigned long long pixelRate;
	@property size_t width;
@end
@interface VCParticipantStats : NSObject
{
}

	@property NSMutableString* id;
	@property NSMutableString* name;
	@property NSMutableArray* remoteCameraStats;
	@property NSMutableArray* remoteMicrophoneStats;
	@property NSMutableArray* remoteWindowShareStats;
	@property NSMutableString* userId;
@end
@interface VCRateShaperStats : NSObject
{
}

	@property unsigned int delayNormal;
	@property unsigned int delayRetransmit;
	@property unsigned int dropNormal;
	@property unsigned int packetsNormal;
	@property unsigned int packetsRetransmit;
@end
@interface VCRemoteMicrophoneStats : NSObject
{
}

	@property unsigned int bitsPerSample;
	@property unsigned int codecDtx;
	@property NSMutableString* codecName;
	@property unsigned int codecQualitySetting;
	@property NSMutableString* id;
	@property int lastFrameMs;
	@property NSMutableArray* localSpeakerStreams;
	@property NSMutableString* name;
	@property unsigned int numberOfChannels;
	@property size_t receiveNetworkBitRate;
	@property long receiveNetworkDelay;
	@property size_t receiveNetworkDroppedPackets;
	@property unsigned int receiveNetworkJitter;
	@property size_t receiveNetworkPacketsConcealed;
	@property size_t receiveNetworkPacketsLost;
	@property unsigned int sampleRateMeasured;
	@property unsigned int sampleRateSet;
@end
@interface VCRemoteRendererStreamStats : NSObject
{
}

	@property unsigned int codecFir;
	@property unsigned int codecIFrames;
	@property unsigned int codecLayers;
	@property unsigned int codecNacks;
	@property NSMutableString* codecName;
	@property unsigned int fps;
	@property unsigned int fpsInput;
	@property unsigned int fpsSent;
	@property size_t framesDropped;
	@property size_t height;
	@property size_t lastHeight;
	@property size_t lastWidth;
	@property NSMutableString* name;
	@property unsigned int sendNetworkBitRate;
	@property long sendNetworkRtt;
	@property size_t width;
@end
@interface VCRemoteSpeakerStreamStats : NSObject
{
}

	@property unsigned int bitsPerSample;
	@property unsigned int codecDtx;
	@property NSMutableString* codecName;
	@property unsigned int codecQualitySetting;
	@property NSMutableString* name;
	@property unsigned int numberOfChannels;
	@property unsigned int sampleRate;
	@property unsigned int sendNetworkBitRate;
	@property long sendNetworkRtt;
@end
@interface VCRemoteVideoSourceStats : NSObject
{
}

	@property size_t codecFir;
	@property size_t codecIFrames;
	@property size_t codecLayers;
	@property size_t codecNacks;
	@property NSMutableString* codecName;
	@property size_t fpsDecoded;
	@property size_t fpsDecoderInput;
	@property size_t fpsRendered;
	@property size_t height;
	@property NSMutableString* id;
	@property int lastFrameMs;
	@property NSMutableArray* localRendererStreams;
	@property unsigned int maxStreamFrameRate;
	@property size_t maxStreamHeight;
	@property size_t maxStreamWidth;
	@property NSMutableString* name;
	@property size_t receiveNetworkBitRate;
	@property size_t receiveNetworkPacketsConcealed;
	@property size_t receiveNetworkPacketsLost;
	@property size_t receiveNetworkPacketsReordered;
	@property size_t receiveNetworkRecoveredWithFec;
	@property unsigned int showFrameRate;
	@property size_t showHeight;
	@property unsigned long long showPixelRate;
	@property NSMutableString* showState;
	@property size_t showWidth;
	@property int videoDeltaFromAudioMs;
	@property size_t width;
@end
@interface VCRoomStats : NSObject
{
}

	@property unsigned int availableDecodeBwPercent;
	@property unsigned int availableDecodeCpuPercent;
	@property unsigned int availableEncodeBwPercent;
	@property unsigned int availableEncodeCpuPercent;
	@property VCBandwidthSummaryStats* bandwidthApp;
	@property VCBandwidthSummaryStats* bandwidthAudio;
	@property VCBandwidthSummaryStats* bandwidthVideo;
	@property NSMutableString* callId;
	@property NSMutableString* conferenceId;
	@property unsigned int cpuUsage;
	@property unsigned long long currentBandwidthDecodePixelRate;
	@property unsigned long long currentBandwidthEncodePixelRate;
	@property unsigned long long currentCpuDecodePixelRate;
	@property unsigned long long currentCpuEncodePixelRate;
	@property NSMutableString* id;
	@property unsigned long long maxDecodePixelRate;
	@property unsigned long long maxEncodePixelRate;
	@property unsigned int maxVideoSources;
	@property NSMutableArray* participantGenerationStats;
	@property NSMutableArray* participantStats;
	@property VCRateShaperStats* rateShaperApp;
	@property VCRateShaperStats* rateShaperAudio;
	@property VCRateShaperStats* rateShaperVideo;
	@property unsigned long long receiveBitRateAvailable;
	@property unsigned long long receiveBitRateTotal;
	@property NSMutableString* reflectorId;
	@property unsigned long long sendBitRateAvailable;
	@property unsigned long long sendBitRateTotal;
	@property unsigned int staticSources;
	@property NSMutableArray* transportInformation;
@end
@interface VCUserStats : NSObject
{
}

	@property NSMutableString* host;
	@property NSMutableString* id;
	@property VCLatencyTestStats* latencyTestStats;
	@property unsigned int port;
	@property NSMutableArray* roomStats;
	@property NSMutableString* serviceType;
@end
