//
//	VidyoContact_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@class VCContactProperty;
typedef NS_ENUM(NSInteger, VCContactPresenceState){
	VCContactPresenceStateUnavailable,
	VCContactPresenceStateDoNotDisturb,
	VCContactPresenceStateExtendedAway,
	VCContactPresenceStateAway,
	VCContactPresenceStateAvailable,
	VCContactPresenceStateInterestedInChat
};
typedef NS_ENUM(NSInteger, VCContactSubscriptionState){
	VCContactSubscriptionStateUnavailable,
	VCContactSubscriptionStateNotSubscribed,
	VCContactSubscriptionStatePreapproved,
	VCContactSubscriptionStateAwaitingApproval,
	VCContactSubscriptionStateSubscribed
};
@interface VCContact : NSObject
{
}

	@property NSMutableString* department;
	@property NSMutableArray* emails;
	@property NSMutableArray* groups;
	@property NSMutableString* handle;
	@property NSMutableString* id;
	@property NSMutableString* name;
	@property NSMutableString* nickname;
	@property NSMutableString* photo;
	@property VCContactPresenceState presenceState;
	@property NSMutableString* presenceStatus;
	@property VCContactSubscriptionState publicationState;
	@property VCContactSubscriptionState subscriptionState;
	@property NSMutableArray* telephones;
	@property long timestamp;
	@property NSMutableString* title;
@end
@interface VCContactProperty : NSObject
{
}

	@property NSMutableArray* types;
	@property NSMutableString* value;
@end
