//
//	VidyoApplication_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoEndpoint_Objc.h"
typedef NS_ENUM(NSInteger, VCApplicationDownloadFailedReason){
	APPLICATION_DOWNLOADFAILEDREASON_WebProxyAuthenticationRequired,
	APPLICATION_DOWNLOADFAILEDREASON_MiscError
};
@protocol VCApplicationIRegisterUpdaterEventListener

	-(void) downloadCompletedCallback:(NSMutableString*)version DownloadedFile:(NSMutableString*)downloadedFile;
	-(void) downloadFailedCallback:(VCApplicationDownloadFailedReason)reason;
@end
@interface VCApplication : NSObject
{
	void* objPtr;
	@public
	id<VCApplicationIRegisterUpdaterEventListener> applicationIRegisterUpdaterEventListener;
}

	-(id) init:(VCEndpoint*)endpoint;
	-(void) dealloc;
	-(BOOL) registerUpdaterEventListener:(id<VCApplicationIRegisterUpdaterEventListener>)applicationIRegisterUpdaterEventListener;
	-(void) setWebProxyCredentials:(const char*)webProxyUserName WebProxyPassword:(const char*)webProxyPassword;
	-(BOOL) startUpdateService:(const char*)currentVersion WorkingDirectory:(const char*)workingDirectory Server:(const char*)server CaFilePath:(const char*)caFilePath WebProxyUsername:(const char*)webProxyUsername WebProxyPassword:(const char*)webProxyPassword;
	-(void) stopUpdateService;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
