//
//	VidyoMeeting_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoMeetingAttendee_Objc.h"
@class VCMeeting;
typedef NS_ENUM(NSInteger, VCMeetingActionResult){
	VCMeetingActionResultOk,
	VCMeetingActionResultNoRecord,
	VCMeetingActionResultNoResponse,
	VCMeetingActionResultUnauthorized,
	VCMeetingActionResultMiscLocalError,
	VCMeetingActionResultMiscRemoteError
};
typedef NS_ENUM(NSInteger, VCMeetingAttendeesSearchResult){
	VCMeetingAttendeesSearchResultOk,
	VCMeetingAttendeesSearchResultIndexOutOfRange,
	VCMeetingAttendeesSearchResultNoRecords,
	VCMeetingAttendeesSearchResultNoResponse,
	VCMeetingAttendeesSearchResultMiscLocalError,
	VCMeetingAttendeesSearchResultMiscRemoteError
};
@protocol VCIMeetingFeedback
@optional

	-(void) getMeetingAttendeeResults:(VCMeeting*)meeting AttendeeList:(NSMutableArray*)attendeeList SearchResult:(VCMeetingAttendeesSearchResult)searchResult CurrentIndex:(unsigned int)currentIndex NumRecords:(unsigned int)numRecords;
@end
@interface VCMeetingFeedback : NSObject<VCIMeetingFeedback>
{
	void* objPtr;
}
	-(id) init;
	-(void) dealloc;
	-(void*)getObjectPtr;
@end
@interface VCMeeting : NSObject
{
	void* objPtr;
}

	@property NSMutableString* body;
	@property NSMutableString* endDateTime;
	@property NSMutableString* id;
	@property BOOL isVidyoMeeting;
	@property NSMutableString* location;
	@property int numberOfAttendees;
	@property NSMutableString* ownerEmail;
	@property NSMutableString* ownerName;
	@property NSMutableString* startDateTime;
	@property NSMutableString* subject;
	@property NSMutableString* vidyoMeetingRoomLink;
	-(void) dealloc;
	-(BOOL) getAttendees:(unsigned int)index PageSize:(unsigned int)pageSize;
	-(NSString*) getBody;
	-(NSString*) getEndDateTime;
	-(NSString*) getId;
	-(BOOL) getIsVidyoMeeting;
	-(NSString*) getLocation;
	-(int) getNumberOfAttendees;
	-(NSString*) getOwnerEmail;
	-(NSString*) getOwnerName;
	-(NSString*) getStartDateTime;
	-(NSString*) getSubject;
	-(NSString*) getVidyoMeetingRoomLink;
	-(NSString*) retrieveBody;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
