//
//	VidyoRemoteSpeaker_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface VCRemoteSpeaker : NSObject
{
	void* objPtr;
}

	-(void) dealloc;
	-(NSString*) getId;
	-(NSString*) getName;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
