//
//	VidyoVideoFrame_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface VCVideoFrame : NSObject
{
	void* objPtr;
}

	@property long data;
	@property long dataCb;
	@property long dataCr;
	@property long dataY;
	@property long elapsedTime;
	@property NSMutableString* format;
	@property size_t height;
	@property size_t heightCb;
	@property size_t heightCr;
	@property size_t heightY;
	@property size_t offsetCb;
	@property size_t offsetCr;
	@property size_t offsetY;
	@property size_t pitchCb;
	@property size_t pitchCr;
	@property size_t pitchY;
	@property size_t size;
	@property size_t sizeCb;
	@property size_t sizeCr;
	@property size_t sizeY;
	@property long timestamp;
	@property size_t width;
	@property size_t widthCb;
	@property size_t widthCr;
	@property size_t widthY;
	-(void) dealloc;
	-(long) getData;
	-(long) getDataCb;
	-(long) getDataCr;
	-(long) getDataY;
	-(long) getElapsedTime;
	-(NSString*) getFormat;
	-(size_t) getHeight;
	-(size_t) getHeightCb;
	-(size_t) getHeightCr;
	-(size_t) getHeightY;
	-(size_t) getOffsetCb;
	-(size_t) getOffsetCr;
	-(size_t) getOffsetY;
	-(size_t) getPitchCb;
	-(size_t) getPitchCr;
	-(size_t) getPitchY;
	-(size_t) getSize;
	-(size_t) getSizeCb;
	-(size_t) getSizeCr;
	-(size_t) getSizeY;
	-(long) getTimestamp;
	-(size_t) getWidth;
	-(size_t) getWidthCb;
	-(size_t) getWidthCr;
	-(size_t) getWidthY;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
