//
//	VidyoVirtualShareManager_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoDevice_Objc.h"
#import "VidyoEndpoint_Objc.h"
#import "VidyoLocalMonitor_Objc.h"
#import "VidyoLocalWindowShare_Objc.h"
@interface VCVirtualShareManager : NSObject
{
	void* objPtr;
}

	-(void) dealloc;
	-(BOOL) localMonitorEvent:(VCEndpoint*)endpoint Monitor:(VCLocalMonitor*)monitor State:(VCDeviceState)state;
	-(BOOL) localWindowShareEvent:(VCEndpoint*)endpoint WindowShare:(VCLocalWindowShare*)windowShare State:(VCDeviceState)state;
	-(BOOL) mediaFailedEvent:(VCEndpoint*)endpoint;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
