//
//	VidyoGateway_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, VCGatewayDisconnectReason){
	VCGatewayDisconnectReasonDisconnected,
	VCGatewayDisconnectReasonConnectionLost,
	VCGatewayDisconnectReasonConnectionTimeout,
	VCGatewayDisconnectReasonNoResponse,
	VCGatewayDisconnectReasonTerminated,
	VCGatewayDisconnectReasonMiscLocalError,
	VCGatewayDisconnectReasonMiscRemoteError,
	VCGatewayDisconnectReasonMiscError
};
typedef NS_ENUM(NSInteger, VCGatewayFailReason){
	VCGatewayFailReasonConnectionFailed,
	VCGatewayFailReasonConnectionLost,
	VCGatewayFailReasonConnectionTimeout,
	VCGatewayFailReasonNoResponse,
	VCGatewayFailReasonTerminated,
	VCGatewayFailReasonInvalidToken,
	VCGatewayFailReasonUnableToCreateResource,
	VCGatewayFailReasonNoResponseFromResource,
	VCGatewayFailReasonInvalidResourceId,
	VCGatewayFailReasonResourceFull,
	VCGatewayFailReasonNotMember,
	VCGatewayFailReasonBanned,
	VCGatewayFailReasonMediaNotEnabled,
	VCGatewayFailReasonMediaFailed,
	VCGatewayFailReasonMiscLocalError,
	VCGatewayFailReasonMiscRemoteError,
	VCGatewayFailReasonMiscError
};
typedef NS_ENUM(NSInteger, VCGatewayState){
	VCGatewayStateIdle,
	VCGatewayStateEstablishingConnection,
	VCGatewayStateFindingResource,
	VCGatewayStateConnectingToResource,
	VCGatewayStateEnablingMedia,
	VCGatewayStateConnected
};
@protocol VCGatewayIConnect

	-(void) onSuccess;
	-(void) onFailure:(VCGatewayFailReason)reason;
	-(void) onDisconnected:(VCGatewayDisconnectReason)reason;
@end
@interface VCGateway : NSObject
{
	void* objPtr;
	@public
	id<VCGatewayIConnect> gatewayIConnect;
}

	-(void) dealloc;
	-(BOOL) connect:(const char*)host Token:(const char*)token DisplayName:(const char*)displayName ResourceId:(const char*)resourceId GatewayIConnect:(id<VCGatewayIConnect>)gatewayIConnect;
	-(void) disconnect;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
