//
//	VidyoMeetingInfo_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoMeetingAttendee_Objc.h"
@interface VCMeetingInfo : NSObject
{
}

	@property NSMutableArray* attendees;
	@property NSMutableString* body;
	@property NSMutableString* endDateTime;
	@property NSMutableString* id;
	@property BOOL isVidyoMeeting;
	@property NSMutableString* location;
	@property unsigned int numOfAttendees;
	@property NSMutableString* ownerEmail;
	@property NSMutableString* ownerName;
	@property NSMutableString* startDateTime;
	@property NSMutableString* subject;
	@property unsigned int totalBodyLength;
	@property NSMutableString* vidyoMeetingRoomLink;
@end
