//
//	VidyoEventSchedule_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface VCEventSchedule : NSObject
{
}

	@property NSMutableString* byDay;
	@property NSMutableString* byMonth;
	@property NSMutableString* byMonthDay;
	@property NSMutableString* bySetPos;
	@property NSMutableString* byWeekNum;
	@property NSMutableString* byYearDay;
	@property NSMutableString* count;
	@property NSMutableString* duration;
	@property NSMutableString* endTime;
	@property NSMutableString* eventId;
	@property NSMutableString* frequency;
	@property NSMutableString* interval;
	@property NSMutableString* startTime;
	@property NSMutableString* until;
	@property NSMutableString* weekStartDay;
@end
