//
//	VidyoRemoteCamera_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoLocalRenderer_Objc.h"
typedef NS_ENUM(NSInteger, VCRemoteCameraMode){
	VCRemoteCameraModeDynamic,
	VCRemoteCameraModeStatic
};
typedef NS_ENUM(NSInteger, VCRemoteCameraPosition){
	VCRemoteCameraPositionUnknown,
	VCRemoteCameraPositionFront,
	VCRemoteCameraPositionBack
};
@protocol VCRemoteCameraIRegisterFrameSizeListener

	-(void) onFrameSizeUpdate:(int)width Height:(int)height;
@end
@interface VCRemoteCamera : NSObject
{
	void* objPtr;
	@public
	id<VCRemoteCameraIRegisterFrameSizeListener> remoteCameraIRegisterFrameSizeListener;
}

	@property NSMutableString* id;
	@property NSMutableString* name;
	-(void) dealloc;
	-(long) addToLocalRenderer:(VCLocalRenderer*)localRenderer Mode:(VCRemoteCameraMode)mode;
	-(BOOL) controlPTZ:(int)pan Tilt:(int)tilt Zoom:(int)zoom;
	-(NSString*) getId;
	-(long) getLocalRenderingStreamId:(int)index;
	-(NSString*) getName;
	-(VCRemoteCameraPosition) getPosition;
	-(BOOL) isControllable;
	-(BOOL) registerFrameSizeListener:(id<VCRemoteCameraIRegisterFrameSizeListener>)remoteCameraIRegisterFrameSizeListener;
	-(BOOL) removeFromLocalRenderer:(VCLocalRenderer*)localRenderer;
	-(BOOL) setPositionInLocalRenderer:(VCLocalRenderer*)localRenderer X:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height FrameInterval:(long)frameInterval;
	-(BOOL) showCameraControl:(BOOL)show;
	-(BOOL) unregisterFrameSizeListener;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
