//
//	VidyoAudioFrame_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface VCAudioFrame : NSObject
{
	void* objPtr;
}

	@property unsigned int bitsPerSample;
	@property long data;
	@property BOOL discontinuity;
	@property BOOL discontinuityBitPresent;
	@property long elapsedTime;
	@property int energy;
	@property BOOL energyBitPresent;
	@property NSMutableString* format;
	@property size_t numberOfChannels;
	@property size_t numberOfSamples;
	@property size_t sampleRate;
	@property size_t size;
	@property BOOL speech;
	@property BOOL speechBitPresent;
	@property long timestamp;
	-(void) dealloc;
	-(size_t) getBitsPerSample;
	-(long) getData;
	-(BOOL) getDiscontinuity;
	-(BOOL) getDiscontinuityBitPresent;
	-(long) getElapsedTime;
	-(int) getEnergy;
	-(BOOL) getEnergyBitPresent;
	-(NSString*) getFormat;
	-(size_t) getNumberOfChannels;
	-(size_t) getNumberOfSamples;
	-(size_t) getSampleRate;
	-(size_t) getSize;
	-(BOOL) getSpeech;
	-(BOOL) getSpeechBitPresent;
	-(long) getTimestamp;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
