//
//	VidyoProperty_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface VCProperty : NSObject
{
}

	@property NSMutableString* name;
	@property NSMutableString* value;
@end
