//
//	VidyoContactInfo_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@class VCContactInfoProperty;
typedef NS_ENUM(NSInteger, VCContactInfoPresenceState){
	VCContactInfoPresenceStateUnavailable,
	VCContactInfoPresenceStateDoNotDisturb,
	VCContactInfoPresenceStateExtendedAway,
	VCContactInfoPresenceStateAway,
	VCContactInfoPresenceStateAvailable,
	VCContactInfoPresenceStateInterestedInChat
};
@interface VCContactInfo : NSObject
{
}

	@property NSMutableArray* emails;
	@property NSMutableArray* groups;
	@property NSMutableString* handle;
	@property NSMutableString* id;
	@property NSMutableString* name;
	@property NSMutableString* nickname;
	@property NSMutableString* photo;
	@property VCContactInfoPresenceState presenceState;
	@property NSMutableArray* telephones;
	@property long timestamp;
@end
@interface VCContactInfoProperty : NSObject
{
}

	@property NSMutableArray* types;
	@property NSMutableString* value;
@end
