//
//	VidyoMediaFormats_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, VCMediaFormat){
	VCMediaFormatIN16,
	VCMediaFormatFL32,
	VCMediaFormatNULL,
	VCMediaFormatI420,
	VCMediaFormatYU12,
	VCMediaFormatYUYV,
	VCMediaFormatYUY2,
	VCMediaFormatyuvs,
	VCMediaFormat2vuy,
	VCMediaFormatUYVY,
	VCMediaFormatHDYC,
	VCMediaFormatyuv2,
	VCMediaFormatyuvu,
	VCMediaFormatNV12,
	VCMediaFormatNV21,
	VCMediaFormat24BG,
	VCMediaFormatraw,
	VCMediaFormatBGRA,
	VCMediaFormatRGBA,
	VCMediaFormatARGB,
	VCMediaFormatBYR1,
	VCMediaFormatBYR2,
	VCMediaFormatJPEG,
	VCMediaFormatMJPG,
	VCMediaFormatdmb1,
	VCMediaFormatavc1,
	VCMediaFormathvc1,
	VCMediaFormatM420,
	VCMediaFormat420f,
	VCMediaFormat420v,
	VCMediaFormatY8
};
