//
//	VidyoRoomInfo_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoChatMessage_Objc.h"
#import "VidyoEndpoint_Objc.h"
@interface VCRoomInfo : NSObject
{
}

	@property long creationTime;
	@property NSMutableString* description;
	@property NSMutableString* extension;
	@property NSMutableString* id;
	@property BOOL isFavorite;
	@property BOOL isMembersOnly;
	@property BOOL isPasswordProtected;
	@property BOOL isPublic;
	@property NSMutableString* language;
	@property unsigned int maxParticipants;
	@property NSMutableArray* messageList;
	@property NSMutableString* name;
	@property int numUsers;
	@property NSMutableArray* ownerList;
	@property VCRoomType type;
	@property NSMutableArray* userList;
@end
