//
//	VidyoChatMessage_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, VCChatMessageSenderType){
	VCChatMessageSenderTypeUser,
	VCChatMessageSenderTypeRoom,
	VCChatMessageSenderTypeSystem,
	VCChatMessageSenderTypeNone
};
typedef NS_ENUM(NSInteger, VCChatMessageType){
	VCChatMessageTypeChat,
	VCChatMessageTypeMediaStart,
	VCChatMessageTypeMediaStop
};
typedef NS_ENUM(NSInteger, VCChatMessageTypingIndication){
	VCChatMessageTypingIndicationActive,
	VCChatMessageTypingIndicationComposing,
	VCChatMessageTypingIndicationGone,
	VCChatMessageTypingIndicationInactive,
	VCChatMessageTypingIndicationPaused,
	VCChatMessageTypingIndicationNone
};
@interface VCChatMessage : NSObject
{
}

	@property NSMutableString* body;
	@property long long id;
	@property VCChatMessageSenderType senderType;
	@property long timestamp;
	@property VCChatMessageType type;
	@property NSMutableString* userId;
@end
