//
//	VidyoLocalSpeaker_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

@interface VCLocalSpeaker : NSObject
{
	void* objPtr;
}

	@property NSMutableString* id;
	@property NSMutableString* name;
	-(void) dealloc;
	-(NSString*) getId;
	-(NSString*) getName;
	-(unsigned int) getVolume;
	-(BOOL) isPaused;
	-(void) pause;
	-(void) playTone:(char)dtmfTone;
	-(void) resume;
	-(void) setVolume:(unsigned int)volumePercent;
	-(void) stopSound;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
