//
//	VidyoLocalRenderer_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, VCLocalRendererBorderStyle){
	VCLocalRendererBorderStyleNone,
	VCLocalRendererBorderStyleSame,
	VCLocalRendererBorderStyleHighlight,
	VCLocalRendererBorderStyleFlash
};
typedef NS_ENUM(NSInteger, VCLocalRendererViewStyle){
	VCLocalRendererViewStyleDefault,
	VCLocalRendererViewStyleTiles,
	VCLocalRendererViewStyleTilesWithRemoteCameraControlV2
};
@protocol VCLocalRendererIRegisterPipEventListener

	-(void) onPipLocationChanged:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height IsExpanded:(BOOL)isExpanded;
@end
@interface VCLocalRenderer : NSObject
{
	void* objPtr;
	@public
	id<VCLocalRendererIRegisterPipEventListener> localRendererIRegisterPipEventListener;
}

	@property NSMutableString* id;
	@property NSMutableString* name;
	-(void) dealloc;
	-(BOOL) disable;
	-(void) enableSelfViewCustomLayout:(BOOL)enable;
	-(NSString*) getId;
	-(NSString*) getName;
	-(BOOL) isPaused;
	-(BOOL) isSelectedTileControllingRemoteCamera;
	-(void) pause;
	-(BOOL) registerPipEventListener:(id<VCLocalRendererIRegisterPipEventListener>)localRendererIRegisterPipEventListener;
	-(void) resume;
	-(BOOL) setAllowContentMultiScreen:(BOOL)allow DisplayIndex:(unsigned int)displayIndex;
	-(BOOL) setAllowPreviewMultiScreen:(BOOL)allow DisplayIndex:(unsigned int)displayIndex;
	-(BOOL) setAnimationSpeed:(unsigned int)speedPercentage;
	-(BOOL) setBackgroundColor:(unsigned char)red Green:(unsigned char)green Blue:(unsigned char)blue;
	-(void) setBorderStyle:(VCLocalRendererBorderStyle)style;
	-(BOOL) setCropped:(BOOL)cropped;
	-(BOOL) setMaxStreams:(unsigned int)numStreams;
	-(BOOL) setMaxStreamsMultiScreen:(unsigned int)numStreams DisplayIndex:(unsigned int)displayIndex;
	-(BOOL) setPosition:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height;
	-(BOOL) setPriorityMultiScreen:(unsigned int)priority DisplayIndex:(unsigned int)displayIndex;
	-(BOOL) setTilesBackgroundColor:(unsigned char)red Green:(unsigned char)green Blue:(unsigned char)blue;
	-(BOOL) showAudioMeters:(BOOL)showMeters;
	-(BOOL) showDebugStats:(BOOL)showStats;
	-(BOOL) showLabel:(BOOL)showLabel;
	-(BOOL) unregisterPipEventListener;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
