//
//	VidyoRemoteMicrophone_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoDevice_Objc.h"
#import "VidyoLocalSpeaker_Objc.h"
typedef NS_ENUM(NSInteger, VCRemoteMicrophoneMode){
	VCRemoteMicrophoneModeDynamic,
	VCRemoteMicrophoneModeStatic
};
@interface VCRemoteMicrophone : NSObject
{
	void* objPtr;
}

	@property NSMutableString* id;
	@property NSMutableString* name;
	@property VCDeviceAudioSignalType signalType;
	-(void) dealloc;
	-(BOOL) addToLocalSpeaker:(VCLocalSpeaker*)speaker Mode:(VCRemoteMicrophoneMode)mode;
	-(NSString*) getId;
	-(NSString*) getName;
	-(VCDeviceAudioSignalType) getSignalType;
	-(BOOL) removeFromLocalSpeaker:(VCLocalSpeaker*)speaker;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
