//
//	VidyoMeetingAttendee_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, VCAttendeeParticipationRole){
	VCAttendeeParticipationRoleChair,
	VCAttendeeParticipationRoleRequired,
	VCAttendeeParticipationRoleOptional,
	VCAttendeeParticipationRoleInformational
};
typedef NS_ENUM(NSInteger, VCAttendeeParticipationStatus){
	VCAttendeeParticipationStatusNeedsAction,
	VCAttendeeParticipationStatusOrganized,
	VCAttendeeParticipationStatusAccepted,
	VCAttendeeParticipationStatusDeclined,
	VCAttendeeParticipationStatusTentative,
	VCAttendeeParticipationStatusDelegated,
	VCAttendeeParticipationStatusNone,
	VCAttendeeParticipationStatusCompleted,
	VCAttendeeParticipationStatusInProcess
};
@interface VCMeetingAttendee : NSObject
{
}

	@property NSMutableString* email;
	@property NSMutableString* name;
	@property VCAttendeeParticipationRole role;
	@property VCAttendeeParticipationStatus status;
@end
