//
//	VidyoCalendarConnProps_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

typedef NS_ENUM(NSInteger, VCCalendarConnectParamType){
	VCCalendarConnectParamTypeUnknown,
	VCCalendarConnectParamTypeUserId,
	VCCalendarConnectParamTypePasswordToken,
	VCCalendarConnectParamTypeMailbox,
	VCCalendarConnectParamTypeServerAddress
};
@interface VCCalendarConnProps : NSObject
{
}

	@property VCCalendarConnectParamType propType;
	@property NSMutableString* propValue;
@end
