//
//	VidyoLocalWindowShare_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoLocalRenderer_Objc.h"
#import "VidyoRemoteRenderer_Objc.h"
typedef NS_ENUM(NSInteger, VCLocalWindowShareState){
	VCLocalWindowShareStateOk,
	VCLocalWindowShareStateNotVisible,
	VCLocalWindowShareStateMinimized,
	VCLocalWindowShareStateClosed,
	VCLocalWindowShareStateMiscError
};
@protocol VCLocalWindowShareIGetApplicationIconFrameDataUriAsync

	-(void) onApplicationIconDataUriComplete:(NSString*)icon;
@end
@protocol VCLocalWindowShareIGetPreviewFrameDataUriAsync

	-(void) onPreviewDataUriComplete:(NSString*)videoFrame State:(VCLocalWindowShareState)state;
@end
@interface VCLocalWindowShare : NSObject
{
	void* objPtr;
	@public
	id<VCLocalWindowShareIGetApplicationIconFrameDataUriAsync> localWindowShareIGetApplicationIconFrameDataUriAsync;
	id<VCLocalWindowShareIGetPreviewFrameDataUriAsync> localWindowShareIGetPreviewFrameDataUriAsync;
}

	@property NSMutableString* applicationName;
	@property NSMutableString* id;
	@property NSMutableString* name;
	-(void) dealloc;
	-(long) addToLocalRenderer:(VCLocalRenderer*)renderer;
	-(BOOL) addToRemoteRenderer:(VCRemoteRenderer*)remoteRenderer;
	-(void) clearConstraints;
	-(BOOL) getApplicationIconFrameDataUriAsync:(size_t)maxWidth MaxHeight:(size_t)maxHeight LocalWindowShareIGetApplicationIconFrameDataUriAsync:(id<VCLocalWindowShareIGetApplicationIconFrameDataUriAsync>)localWindowShareIGetApplicationIconFrameDataUriAsync;
	-(NSString*) getApplicationName;
	-(NSString*) getId;
	-(NSString*) getName;
	-(BOOL) getPreviewFrameDataUriAsync:(size_t)maxWidth MaxHeight:(size_t)maxHeight LocalWindowShareIGetPreviewFrameDataUriAsync:(id<VCLocalWindowShareIGetPreviewFrameDataUriAsync>)localWindowShareIGetPreviewFrameDataUriAsync;
	-(NSString*) getPreviewLabel;
	-(unsigned int) getProcessId;
	-(NSString*) getProcessName;
	-(NSString*) getUpdatedName;
	-(BOOL) isApplicationNameSet;
	-(BOOL) isNameSet;
	-(BOOL) removeFromLocalRenderer:(VCLocalRenderer*)renderer;
	-(BOOL) removeFromRemoteRenderer:(VCRemoteRenderer*)remoteRenderer;
	-(BOOL) setBoundsConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval MaxWidth:(unsigned int)maxWidth MinWidth:(unsigned int)minWidth MaxHeight:(unsigned int)maxHeight MinHeight:(unsigned int)minHeight;
	-(BOOL) setCapability:(long)frameInterval ShowCursor:(BOOL)showCursor RedactOccludedAreas:(BOOL)redactOccludedAreas;
	-(BOOL) setCursorVisibility:(BOOL)showCursor;
	-(BOOL) setDiscrerteConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval Width:(unsigned int)width Height:(unsigned int)height ScaleFactor:(float)scaleFactor;
	-(BOOL) setFrameInterval:(long)frameInterval;
	-(BOOL) setLowLatencyProfile:(BOOL)profile;
	-(BOOL) setPositionInLocalRenderer:(VCLocalRenderer*)localRenderer X:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height FrameInterval:(long)frameInterval;
	-(BOOL) setPreviewLabel:(NSString*)previewLabel;
	-(BOOL) setRedactOccludedAreas:(BOOL)redactOccludedAreas;
	-(BOOL) setScaleFactor:(float)scaleFactor;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
