//
//	VidyoLocalMonitor_Objc.h
//	VidyoClient
//
//	This file is auto generated, do not edit this file
//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.
//

#import "VidyoLocalRenderer_Objc.h"
#import "VidyoLocalWindowShare_Objc.h"
#import "VidyoRemoteRenderer_Objc.h"
typedef NS_ENUM(NSInteger, VCLocalMonitorState){
	VCLocalMonitorStateOk,
	VCLocalMonitorStateNotVisible,
	VCLocalMonitorStateMiscError
};
@protocol VCLocalMonitorIGetPreviewFrameDataUriAsync

	-(void) onPreviewDataUriComplete:(NSString*)videoFrame State:(VCLocalMonitorState)state;
@end
@interface VCLocalMonitor : NSObject
{
	void* objPtr;
	@public
	id<VCLocalMonitorIGetPreviewFrameDataUriAsync> localMonitorIGetPreviewFrameDataUriAsync;
}

	@property NSMutableString* id;
	@property NSMutableString* name;
	-(void) dealloc;
	-(long) addToLocalRenderer:(VCLocalRenderer*)renderer;
	-(BOOL) addToRemoteRenderer:(VCRemoteRenderer*)remoteRenderer;
	-(void) clearConstraints;
	-(NSString*) getId;
	-(NSString*) getName;
	-(VCLocalMonitorState) getPreviewFrameDataUri:(size_t)maxWidth MaxHeight:(size_t)maxHeight VideoFrame:(NSMutableString*)videoFrame;
	-(BOOL) getPreviewFrameDataUriAsync:(size_t)maxWidth MaxHeight:(size_t)maxHeight LocalMonitorIGetPreviewFrameDataUriAsync:(id<VCLocalMonitorIGetPreviewFrameDataUriAsync>)localMonitorIGetPreviewFrameDataUriAsync;
	-(BOOL) isPrimary;
	-(void) precludeApplication:(VCLocalWindowShare*)w;
	-(void) precludeWindow:(VCLocalWindowShare*)w;
	-(BOOL) removeFromLocalRenderer:(VCLocalRenderer*)renderer;
	-(BOOL) removeFromRemoteRenderer:(VCRemoteRenderer*)remoteRenderer;
	-(BOOL) setBoundsConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval MaxWidth:(unsigned int)maxWidth MinWidth:(unsigned int)minWidth MaxHeight:(unsigned int)maxHeight MinHeight:(unsigned int)minHeight;
	-(BOOL) setCaptureInterval:(long)frameInterval;
	-(BOOL) setDiscrerteConstraints:(long)maxFrameInterval MinFrameInterval:(long)minFrameInterval Width:(unsigned int)width Height:(unsigned int)height ScaleFactor:(float)scaleFactor;
	-(BOOL) setFrameInterval:(long)frameInterval;
	-(BOOL) setLowLatencyProfile:(BOOL)profile;
	-(BOOL) setPositionInLocalRenderer:(VCLocalRenderer*)localRenderer X:(int)x Y:(int)y Width:(unsigned int)width Height:(unsigned int)height FrameInterval:(long)frameInterval;
	-(id) initWithObject:(void*)rPtr;
	-(void*)getObjectPtr;
@end
